[decoration]

[creature]
speed = 3.0
radius = 0.5
alive = true

[enemy]
extends = "creature"
bot = true

[guy]
extends = "creature"
frames = ["guy"]
speed = 5.0

[zombie]
extends = "enemy"
frames = ["zombie"]

[missile]
radius = 0.2
missile = true

[bullet]
extends = "missile"
frames = ["bullet"]
