[decoration]

[particle]
health = 0.3
particle = true

[creature]
solid = true
speed = 3.0
radius = 0.5
shootable = true
health = 10

[enemy]
extends = "creature"
bot = true

[guy]
extends = "creature"
frames = ["guy"]
speed = 5.0
health = 100

[zombie]
extends = "enemy"
frames = ["zombie"]
health = 25

[missile]
solid = true
radius = 0.0
missile = true

[bullet]
extends = "missile"
frames = ["bullet"]


[spatter]
extends = "particle"
frames = ["spatter"]
