[default]
weapon = "pistol"

[decoration]

[particle]
health = 0.3
particle = true

[creature]
solid = true
speed = 3.0
radius = 0.5
shootable = true
health = 10
offset = [0.0, -0.25]

[enemy]
extends = "creature"
bot = true

[guy]
extends = "creature"
frames = ["guy_stand"]
locomotion_frames = ["guy_walk1", "guy_walk2"]
speed = 5.0
health = 100
weapon = "rifle"

[zombie]
extends = "enemy"
frames = ["zombie_stand"]
locomotion_frames = ["zombie_walk1", "zombie_walk2"]
dead_frames = ["zombie_dead1"]
health = 25
speed = 2

[missile]
health = 1
solid = true
radius = 0.0
missile = true
rotate_to_face = true
missile_direct_damage = [10,10]

[fists]
extends = "missile"
frames = []

[bullet]
extends = "missile"
frames = ["bullet"]

[spatter]
extends = "particle"
frames = ["spatter"]
