[decoration]

[creature]
speed = 3.0
radius = 0.5

[enemy]
extends = "creature"
bot = true

[guy]
extends = "creature"
frames = ["guy"]
speed = 5.0

[zombie]
extends = "enemy"
frames = ["zombie"]


[projectile]


[bullet]
extends = "projectile"
frames = ["bullet"]
