[default]
weapon = "pistol"
range = 100.0

[decoration]

[particle]
health = 0.3
particle = true

[creature]
solid = true
speed = 3.0
radius = 0.5
shootable = true
health = 10
offset = [0.0, -0.25]

[enemy]
extends = "creature"
bot = true

[guy]
extends = "creature"
frames = ["guy_stand"]
dead_frames = ["guy_dead"]
locomotion_frames = ["guy_walk1", "guy_walk2"]
speed = 5.0
health = 100
weapon = "rifle"

[zombie]
extends = "enemy"
frames = ["zombie_stand"]
locomotion_frames = ["zombie_walk1", "zombie_walk2"]
dead_frames = ["zombie_dead1"]
health = 25
speed = 2
weapon = "fists"

[missile]
health = 1
solid = true
radius = 0.0
missile = true
rotate_to_face = true
missile_direct_damage = [10,10]
max_age = 10.0
velocity = 30.0

[fists]
extends = "missile"
frames = ["fist"]
max_age = 0.10
velocity = 5.0

[bullet]
extends = "missile"
frames = ["bullet_1", "bullet_2", "bullet_3", "bullet_4"]

[spatter]
extends = "particle"
frames = ["spatter"]
