guy = "images/guy.png"
bullet = "images/bullet.png"
spatter = "images/spatter.png"
zombie_stand = "images/zombie_stand.png"
guy_stand = "images/guy_stand.png"
guy_walk1 = "images/guy_walk1.png"
guy_walk2 = "images/guy_walk2.png"
zombie_walk1 = "images/zombie_walk1.png"
zombie_walk2 = "images/zombie_walk2.png"
zombie_dead1 = "images/zombie_dead1.png"
pistol = "images/pistol.png"
pistol_firing = "images/pistol_firing.png"
machinegun = "images/machinegun.png"
machinegun_firing = "images/machinegun_firing.png"