[fists]
display_name = "Fists"
rate_of_fire = 1
damage = [3,6]

[pistol]
display_name = "Pistol"
frames = ["pistol", "pistol_firing"]
rate_of_fire = 3
damage = [5,10]
grip = [0.33,0.62]
muzzle = [0.75, 0.75]

