[fists]
display_name = "Fists"
rate_of_fire = 3
damage = [3,6]
projectile = "fists"
range = 1.5

[pistol]
display_name = "Pistol"
frames = ["pistol", "pistol_firing"]
rate_of_fire = 3
damage = [5,10]
#mount = [0.33,0.62]
mount_offset = 0.15
muzzle_offset = 1.0
projectile = "bullet"

[rifle]
extends = "pistol"
rate_of_fire = 2
damage = [100,200]

[machinegun]
frames = ["machinegun", "machinegun_firing"]
extends = "pistol"
rate_of_fire = 10
damage = [2,5]
spread = 0.2
